// AUTHENTICATION
export const FETCH_AUTH_LOGIN = 'FETCH_AUTH_LOGIN'
export const RECEIVE_AUTH_LOGIN = 'RECEIVE_AUTH_LOGIN'
export const RECEIVE_AUTH_USER_LOGIN = 'RECEIVE_AUTH_USER_LOGIN'
export const RECEIVE_AUTH_USER_TOKEN_LOGIN = 'RECEIVE_AUTH_USER_TOKEN_LOGIN'
export const AUTHENTICATED = 'AUTHENTICATED'
export const LOGOUT = 'LOGOUT'
export const SUCCESS_AUTH_LOGIN = 'SUCCESS_AUTH_LOGIN'
export const SUCCESS_AUTH_LOGOUT = 'SUCCESS_AUTH_LOGOUT'
export const FAILED_AUTH_LOGIN = 'FAILED_AUTH_LOGIN'

// USER
export const FETCH_MEMBER = 'FETCH_MEMBER'
export const RECEIVE_MEMBER = 'RECEIVE_MEMBER'
export const SUCCESS_MEMBER = 'SUCCESS_MEMBER'
export const FAILED_MEMBER = 'FAILED_MEMBER'